=== AkarshiBansal2147238/FacultyManagementChrist/Christ University/emp1.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ChristUniversity">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Faculty">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="No._of_Organizations_worked_with" type="xs:unsignedByte" />
              <xs:element name="Years" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AkarshiBansal2147238/FacultyManagementChrist/Christ University/faculty.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="test.xsl"?>
<ChristUniversity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emp1.xsd">
   <Faculty>
      <Name>Rithul</Name>
      <No._of_Organizations_worked_with>10</No._of_Organizations_worked_with>
      <Years>22</Years>
   </Faculty>
   <Faculty>
      <Name>Indu</Name>
      <No._of_Organizations_worked_with>3</No._of_Organizations_worked_with>
      <Years>14</Years>
   </Faculty>
   <Faculty>
      <Name>Kevin</Name>
      <No._of_Organizations_worked_with>2</No._of_Organizations_worked_with>
      <Years>10</Years>
   </Faculty>
</ChristUniversity>
